/**
 * Created by 叶子 on 2017/7/30.
 */
export const REQUEST_DATA = 'REQUEST_DATA';

export const RECEIVE_DATA = 'RECEIVE_DATA';

export const REQUESTMAPTABLE_DATA = 'REQUESTMAPTABLE_DATA';

export const REQUESTMAPLIST_DATA = 'REQUESTMAPLIST_DATA';